name: github-action
on:
  push:
    branches:
      # When someone push to `main` branch
      - main
  pull_request:
    branches:
      - main
jobs:
  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      
      - run: npm run test
        env:
          CI: true



  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: "Deploy to staging"
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Checkout the repo on the Staging Server
        run: ssh staging "git pull https://github.com/chefon1/try1.git || true"
           
      - name: Install
        run: ssh staging 'cd ~/try1 && npm install -y'

      - name: Lint
        run: ssh staging 'cd ~/try1 && npm run lint'

      - name: Build
        run: ssh staging 'cd ~/try1 && npm run build'

      - name: prettier
        run: ssh staging 'cd ~/try1 && npm install --save-stage --save-exact prettier'

      - name: Start the app
        timeout-minutes: 2 # Times out after 1 minute
        run: ssh staging 'cd bos1 && npm run start&'